services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/{Command,Service}'

    Symfony\Component\Console\Application:
        public: true